backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "app/assets"
public_folder: "/assets"
display_url: https://www.helsinginlyceumklubi.fi
collections:
  - name: fi
    label: Suomi
    folder: app/pages/fi
    create: false
    fields: # The fields for each document, usually in front matter
#      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
#      - {label: "Publish Date", name: "date", widget: "datetime"}
#      - {label: "Featured Image", name: "thumbnail", widget: "image"}
#      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: se
    label: Ruotsi
    folder: app/pages/se
    create: false
    fields: # The fields for each document, usually in front matter
#      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
#      - {label: "Publish Date", name: "date", widget: "datetime"}
#      - {label: "Featured Image", name: "thumbnail", widget: "image"}
#      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}

